### ISSUE TITLE
Issue when compiling on macOS

### ISSUE THREAD

**Issue by Pomettini** [wendigojaeger/ZigGBA#3]
`/Users/pomettini/Git/ZigGBAHelloWorld/build.zig:8:25: error: container 'std' has no member called 'Target'
    exe.setTheTarget(std.Target {`

Any idea of why this happens? I apologize for the newbie question, but I'm moving my first steps with Zig :)

**Comment by andrewrk** [comment]
double check that your zig version meets this requirement from the README:

> This project assume current Zig master (0.5.0+d28aa38db).

**Comment by wendigojaeger** [comment]
Thanks for the response @andrewrk ! I do have a OSX machine that I could setup to test. 

And @Pomettini, let me known if using the master OS X has issues.

**Comment by wendigojaeger** [comment]
Tried on Mac OS X, I needed to install LLVM using brew and add its destination bin folder to my $PATH but everything works.
